server:
  port: 8090
  tomcat:
    max-threads: 2

management:
  endpoint:
    beans:
      enabled: true  
spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456
      